import os
import re
import datetime
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

EXPORTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../storage/exports"))
os.makedirs(EXPORTS_DIR, exist_ok=True)

class DocumentExporter:
    @staticmethod
    def generate_pdf(title: str, content: str) -> Dict[str, str]:
        """Generates a valid, high-compatibility PDF document."""
        timestamp = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
        clean_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', title)[:30]
        filename = f"Summary_{clean_title}_{timestamp}.pdf"
        file_path = os.path.join(EXPORTS_DIR, filename)

        clean_lines = []
        for line in content.split('\n'):
            # Clean markdown and non-ASCII emojis for robust PDF rendering
            cl = re.sub(r'[\*\#\_]', '', line).strip()
            cl = re.sub(r'[^\x00-\x7F]+', ' ', cl).strip()
            if cl: clean_lines.append(cl)

        pdf_bytes = DocumentExporter._create_simple_pdf_bytes(title, clean_lines)

        with open(file_path, "wb") as f:
            f.write(pdf_bytes)

        return {
            "filename": filename,
            "file_url": f"/api/v1/export/file/{filename}",
            "file_path": file_path
        }

    @staticmethod
    def generate_jpeg(title: str, content: str) -> Dict[str, str]:
        """Generates a HD dark-mode JPEG image infographic card."""
        timestamp = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
        clean_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', title)[:30]
        filename = f"Summary_{clean_title}_{timestamp}.jpg"
        file_path = os.path.join(EXPORTS_DIR, filename)

        clean_lines = []
        for line in content.split('\n'):
            cl = re.sub(r'[\*\#\_]', '', line).strip()
            # Strip non-ASCII unicode emojis to prevent Pillow bitmap font encoding errors
            cl = re.sub(r'[^\x00-\x7F]+', ' ', cl).strip()
            if cl: clean_lines.append(cl)

        img_width = 1200
        line_height = 36
        margin = 60
        header_height = 120

        # Word wrapping lines for JPEG image card
        wrapped_lines = []
        for raw_line in clean_lines:
            words = raw_line.split(' ')
            current_l = ""
            for w in words:
                if len(current_l) + len(w) + 1 > 75:
                    wrapped_lines.append(current_l)
                    current_l = w
                else:
                    current_l = f"{current_l} {w}".strip()
            if current_l:
                wrapped_lines.append(current_l)

        total_content_height = max(500, len(wrapped_lines) * line_height)
        img_height = header_height + margin * 2 + total_content_height

        try:
            from PIL import Image, ImageDraw
            img = Image.new('RGB', (img_width, img_height), color=(15, 23, 42)) # Slate dark theme
            draw = ImageDraw.Draw(img)

            # Header Banner
            draw.rectangle([(0, 0), (img_width, header_height)], fill=(37, 99, 235)) # Buddy AI accent blue
            draw.rectangle([(0, header_height - 6), (img_width, header_height)], fill=(59, 130, 246))

            # Header Text
            safe_header_title = re.sub(r'[^\x00-\x7F]+', ' ', title)[:50]
            draw.text((margin, 35), "AI STUDY BUDDY - LEARNING OS", fill=(255, 255, 255))
            draw.text((margin, 68), f"Executive Summary: {safe_header_title}", fill=(219, 234, 254))

            # Body Text Lines
            y_pos = header_height + margin
            for line_text in wrapped_lines[:60]:
                draw.text((margin, y_pos), line_text, fill=(241, 245, 249))
                y_pos += line_height

            # Footer Banner
            draw.rectangle([(0, img_height - 50), (img_width, img_height)], fill=(30, 41, 59))
            draw.text((margin, img_height - 35), "Generated by AI Study Buddy • 100% Grounded Context", fill=(148, 163, 184))

            img.save(file_path, "JPEG", quality=95)
            print(f"[EXPORTER SUCCESS] Saved HD JPEG image card to {file_path}")
            return {
                "filename": filename,
                "file_url": f"/api/v1/export/file/{filename}",
                "file_path": file_path
            }
        except Exception as e:
            logger.error(f"Pillow image generation error: {e}")

        # Fallback PDF generator if image rendering fails
        pdf_res = DocumentExporter.generate_pdf(title, content)
        return pdf_res

    @staticmethod
    def _create_simple_pdf_bytes(title: str, lines: list) -> bytes:
        """Constructs a 100% valid PDF stream binary."""
        pdf_stream = []
        pdf_stream.append("BT")
        pdf_stream.append("/F1 12 Tf")
        pdf_stream.append("50 740 Td")
        pdf_stream.append("16 TL")

        safe_title = re.sub(r'[^\x00-\x7F]+', ' ', title).replace('(', '\\(').replace(')', '\\)').replace('\\', '\\\\')
        pdf_stream.append(f"({safe_title}) '")
        pdf_stream.append("(--------------------------------------------------) '")

        for line in lines[:40]:
            safe_line = line.replace('(', '\\(').replace(')', '\\)').replace('\\', '\\\\')
            pdf_stream.append(f"({safe_line}) '")

        pdf_stream.append("ET")
        stream_data = "\n".join(pdf_stream).encode('latin-1', errors='ignore')

        objects = []
        objects.append(b"%PDF-1.4\n")
        objects.append(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
        objects.append(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")
        objects.append(b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n")
        objects.append(f"4 0 obj\n<< /Length {len(stream_data)} >>\nstream\n".encode() + stream_data + b"\nendstream\nendobj\n")
        objects.append(b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

        xref = b"xref\n0 6\n0000000000 65535 f \n"
        pos = len(objects[0])
        for obj in objects[1:]:
            xref += f"{pos:010d} 00000 n \n".encode()
            pos += len(obj)

        trailer = f"trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{pos}\n%%EOF\n".encode()
        return b"".join(objects) + xref + trailer
